### PR TITLE
Suggestion: Trigger and condition for top/bottom X hours today

### PR DESCRIPTION
**Pull request by haugene**
This is a feature that I've missed as I'm thinking of having the water heater turn off for the most expensive hours of the day. And even if there are other triggers and conditions, they don't fit the use case completely.
The implementation here is probably a bit faulty. I'm not a JS developer and I have not tested this any way. I have probably missed some Homey syntax as well.

Anyways. I thought I'd give it a shot and hope that this can serve as a good start to the implementation or at least a discussion of the functionality. I'm happy to help if there's anything I can do but I don't have a good development environment for this and would probably need some pointers on how to test/simulate usage.

### CODE REVIEW

**Comment by lovetibber** [comment]
hey @haugene, would you be able to use the priceLevel for this or would that not work for this use case?

**Comment by haugene** [comment]
hey @lovetibber. I was looking into that first, thinking that it would solve it. But the GraphQL documentation says:
> Price level based on trailing price average (3 days for hourly values and 30 days for daily values)

Since it's not relative to a single day, this means that if prices go up a whole day can be classified as "expensive" or higher. And I can't have the hot water go cold for a whole day. The objective is to avoid the most expensive hours within a day, and not expensive period across days.

I could try a setup with priceLevel, it might do the job. Maybe do some other magic to avoid it keeping stuff turned off for too long. But the functionality I propose would be much more explicit. You could choose to turn things on/off for the least/most expensive X hours of the day. That would avoid the peaks but still run for a minimum amount of hours regardless of price.

But I will think more on a control-function built around priceLevel and a max consecutive power-off check or something similar.

**Comment by lovetibber** [comment]
hey @haugene, got it - that makes sense.
How about you give that a go, and if you realize it isn't as accurate as you'd like we'll check it out?

**Comment by 4Fire4** [comment]
@toini please add this flow card to the app. I don't see how this could be solved with existing app functionality: "Current hourly price is amongst the x cheapest hours today"

**Comment by lovethyresson** [comment]
Good suggestion, we’ll look into it.

Thanks!
Love

**Comment by toini** [comment]
I merged it but ran into troubles when building:

$ homey app build
✖ Homey App did not validate against level `debug`:
Found multiple Flow card triggers with the id "current.L1_changed", all Flow cards should have a unique id.

Assuming the deploy process has changed and now requires unique flow card ids accross the app. Currently we share them between pulse and watty. Apparently we need a migration?

**Comment by jstaro** [comment]
This should be building again.
It will also be part of the upcoming official release.

**Pull request merged**
